# Following https://wiki.alpinelinux.org/wiki/K8s
- name: K8s setup
  hosts: myhosts
  vars:
    alpine_version: "3.24"
  tasks:
    - name: Ping the hosts
      ansible.builtin.ping:
    
    - name: Setup Repositories
      ansible.builtin.template:
        src: templates/etc_apk_repositories.j2
        dest: /etc/apk/repositories

    - name: Boot-time br_netfilter module
      ansible.builtin.lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: br_netfilter
        create: yes

    - name: Load br_netfilter module
      community.general.modprobe:
        name: br_netfilter
        state: present

    - name: Enable ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip.forward
        value: '1'
        state: present
        reload: true

    - name: Enable bridge iptables
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        state: present
        reload: true

    - name: Install packages
      community.general.apk:
        name: cni-plugin-flannel,cni-plugins,flannel,flannel-contrib-cni,kubelet,kubeadm,kubectl,containerd,uuidgen
        state: present

    - name: Remove swap fstab entry
      ansible.builtin.lineinfile:
        backup: true
        backrefs: yes
        regexp: '^[^#](.*swap.*)$'
        line: '# \1'
        path: /etc/fstab

    - name: Swapoff
      when: ansible_facts["swaptotal_mb"] > 0
      ansible.builtin.command: swapoff -a

# TODO: Add "Fix prometheus errors section"

    - name: Setup services
      ansible.builtin.shell: |
        set -euxo pipefail
        uuidgen > /etc/machine-id
        rc-update add containerd
        rc-update add kubelet
        rc-service containerd start
        rc-update add ntpd
        rc-service ntpd start
        apk add 'kubelet=~1.36'
        apk add 'kubeadm=~1.36'
        apk add 'kubectl=~1.36'

    - name: Setup flannel
      ansible.builtin.shell: ln -s /usr/libexec/cni/flannel-amd64 /usr/libexec/cni/flannel
      args:
        creates: "/usr/libexec/cni/flannel"


# TODO: Validate: Should bump containerd sandbox_image?

#    - name: Print ansible facts
#      ansible.builtin.debug:
#        var: ansible_facts

